### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by EsmaeilMohamed** [ShabanKamell/RxLocation#1]
hey @ShabanKamell 
when i try to implement your dependency
this error happened to me
Failed to resolve: com.sha.kamel:rx-location:1.8.0
and i want to ask another questin
how can wait until device get location ????

**Comment by ShabanKamell** [comment]
Hey @EsmaeilMohamed,

The issue can be resolved by adding this in root project build.gradle:
repositories {
...
    maven {
        url  "https://dl.bintray.com/shabankamel/android" 
    }
}

This is an issue in [Bintray](https://bintray.com/) where  i deploy the library and will try to fix it soon.

When you call subscrib, the location will passed to you when it's retrieved:

.subscribe(location -> {
// When the device sends the location it will be available here. So implement your logic here
// See app module for the complete example
}

Thanks for your comment :)
